-- AlterTable
ALTER TABLE "Maker" ADD COLUMN     "infillPercent" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "wallThicknessMm" DOUBLE PRECISION NOT NULL DEFAULT 1.2,
ADD COLUMN     "supportCoefficient" DOUBLE PRECISION NOT NULL DEFAULT 1.15;
